import React from 'react';
import { AlertCircle, Copy } from 'lucide-react';
import type { DbStatus } from '../types';

interface DbSetupBannerProps {
  dbStatus: DbStatus;
  onRecheck: () => void;
}

const SQL = `-- 1. Table 'pets'
CREATE TABLE IF NOT EXISTS pets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  species TEXT NOT NULL,
  breed TEXT,
  color TEXT,
  description TEXT,
  location TEXT,
  lat FLOAT,
  lng FLOAT,
  contact TEXT,
  image_url TEXT,
  name TEXT DEFAULT 'Inconnu',
  pet_status TEXT DEFAULT 'toujours_errant',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Colonnes manquantes
ALTER TABLE pets ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'Inconnu';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS pet_status TEXT DEFAULT 'toujours_errant';

-- 3. Table 'matches'
CREATE TABLE IF NOT EXISTS matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lost_report_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  found_report_id BIGINT REFERENCES pets(id) ON DELETE CASCADE,
  match_score INT,
  distance_km FLOAT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RLS (Row Level Security) - optional but recommended
ALTER TABLE pets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON pets FOR SELECT USING (true);
CREATE POLICY "Authenticated insert" ON pets FOR INSERT WITH CHECK (true);

ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON matches FOR SELECT USING (true);
`;

export default function DbSetupBanner({ dbStatus, onRecheck }: DbSetupBannerProps) {
  if (dbStatus.petsTable && dbStatus.matchesTable && dbStatus.missingColumns.length === 0) {
    return null;
  }

  return (
    <div className="bg-red-50 border-b border-red-100 px-6 py-4 space-y-3">
      <div className="flex items-center gap-2 text-red-700 font-bold text-sm">
        <AlertCircle size={18} /> Configuration Supabase requise
      </div>
      <p className="text-xs text-red-600 leading-relaxed">
        Certaines tables manquent. Copiez et exécutez ce SQL dans le <b>SQL Editor de Supabase</b> :
      </p>
      <div className="bg-stone-900 text-stone-300 p-3 rounded-xl font-mono text-[10px] overflow-x-auto relative group max-h-48 overflow-y-auto">
        <pre className="whitespace-pre-wrap">{SQL}</pre>
        <button
          onClick={() => { navigator.clipboard.writeText(SQL); alert('SQL copié !'); }}
          className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 p-2 rounded-lg transition-colors"
        >
          <Copy size={14} />
        </button>
      </div>
      <button onClick={onRecheck} className="text-[10px] font-bold text-red-700 underline hover:no-underline">
        Vérifier à nouveau
      </button>
    </div>
  );
}
